
spring:
  security:
    oauth2:
      client:
        registration:
          idporten:
           client-id: oidc_digdircamp21_issuer_test1
           client-secret: 285fd3a7-3c5c-4ed0-be1e-2f80732d359e
           scope: openid
        provider:
         idporten:
          issuer-uri: https://oidc-test1.difi.eon.no/idporten-oidc-provider/
server:
  port: 8083